// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkgepdt1u0afuS9gYJypl3LuRbHgTbi5c',
    appId: '1:275179618795:web:3ee98f455483192ca519ae',
    messagingSenderId: '275179618795',
    projectId: 'gig-connect-ccdbe',
    authDomain: 'gig-connect-ccdbe.firebaseapp.com',
    storageBucket: 'gig-connect-ccdbe.firebasestorage.app',
    measurementId: 'G-V55X11VT0C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoezcpV1hcDfZEzO-YvcxgS0fAVzeiRtE',
    appId: '1:275179618795:android:c7c04b860c2a0b94a519ae',
    messagingSenderId: '275179618795',
    projectId: 'gig-connect-ccdbe',
    storageBucket: 'gig-connect-ccdbe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMC9n2rp-aNTwSs8dMwJdGvSPEz2jHTIo',
    appId: '1:275179618795:ios:837ea71bf21d7271a519ae',
    messagingSenderId: '275179618795',
    projectId: 'gig-connect-ccdbe',
    storageBucket: 'gig-connect-ccdbe.firebasestorage.app',
    iosClientId: '275179618795-upb5jsrt7ihcemofd941svjn6npnnhn0.apps.googleusercontent.com',
    iosBundleId: 'com.example.gigConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMC9n2rp-aNTwSs8dMwJdGvSPEz2jHTIo',
    appId: '1:275179618795:ios:837ea71bf21d7271a519ae',
    messagingSenderId: '275179618795',
    projectId: 'gig-connect-ccdbe',
    storageBucket: 'gig-connect-ccdbe.firebasestorage.app',
    iosClientId: '275179618795-upb5jsrt7ihcemofd941svjn6npnnhn0.apps.googleusercontent.com',
    iosBundleId: 'com.example.gigConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkgepdt1u0afuS9gYJypl3LuRbHgTbi5c',
    appId: '1:275179618795:web:6471cbfbafcb4a3ea519ae',
    messagingSenderId: '275179618795',
    projectId: 'gig-connect-ccdbe',
    authDomain: 'gig-connect-ccdbe.firebaseapp.com',
    storageBucket: 'gig-connect-ccdbe.firebasestorage.app',
    measurementId: 'G-3GWHT3ETBB',
  );

}